version: '3'

volumes:
  production_postgres_data: { }
  production_postgres_data_backups: { }
  production_traefik: { }
  production_django_media: { }

services:
  django: &django
    build:
      context: .
      dockerfile: ./compose/production/django/Dockerfile

    image: app_production_django
    volumes:
      - /var/www/bot.makromarket.uz/media:/app/media
      - /var/www/bot.makromarket.uz/static:/app/staticfiles
    depends_on:
      - postgres
      - redis
    ports:
      - "5080:5000"
    env_file:
      - ./.envs/.production/.django
      - ./.envs/.production/.postgres
    command: /start

  postgres:
    build:
      context: .
      dockerfile: ./compose/production/postgres/Dockerfile
    image: app_production_postgres
    volumes:
      - production_postgres_data:/var/lib/postgresql/data
      - production_postgres_data_backups:/backups
    env_file:
      - ./.envs/.production/.postgres

  #  traefik:
  #    build:
  #      context: .
  #      dockerfile: ./compose/production/traefik/Dockerfile
  #    image: app_production_traefik
  #    depends_on:
  #      - django
  #    volumes:
  #      - production_traefik:/etc/traefik/acme
  #    ports:
  #      - '0.0.0.0:9001:80'
  #      - '0.0.0.0:9002:443'
  #      - '0.0.0.0:9003:5555'

  redis:
    image: docker.io/redis:6

  celeryworker:
    <<: *django
    image: app_production_celeryworker
    command: /start-celeryworker
    ports: [ ]

  celerybeat:
    <<: *django
    image: app_production_celerybeat
    command: /start-celerybeat
    ports: [ ]

  flower:
    <<: *django
    image: app_production_flower
    command: /start-flower
    ports:
      - "5081:5555"
  bot:
    <<: *django
    image: app_production_python_bot
    container_name: app_local_python_bot
    depends_on:
      - redis
      - postgres
    ports: [ ]
    command: /start-bot

#  nginx:
#    build:
#      context: .
#      dockerfile: ./compose/production/nginx/Dockerfile
#    image: app_local_nginx
#    depends_on:
#      - django
#    volumes:
#      - production_django_media:/usr/share/nginx/media:ro
