# Generated by Django 4.2.9 on 2024-01-30 12:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Promotion",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("name", models.CharField(max_length=100, verbose_name="Название")),
                ("description", models.TextField(verbose_name="Описание")),
                ("description_ru", models.TextField(null=True, verbose_name="Описание")),
                ("description_uz", models.TextField(null=True, verbose_name="Описание")),
                ("start_date", models.DateField(verbose_name="Дата начала")),
                ("end_date", models.DateField(verbose_name="Дата окончания")),
                ("is_active", models.BooleanField(default=True, verbose_name="Активна")),
            ],
        ),
    ]
