# Generated by Django 4.2.9 on 2024-01-30 12:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0003_telegramuser_is_active"),
        ("promotions", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="PromotionCode",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("code", models.CharField(db_index=True, max_length=50, unique=True, verbose_name="Код промо-акции")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "promotion",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="promotions.promotion",
                        verbose_name="Промо-акция",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="users.telegramuser",
                        verbose_name="Пользователь",
                    ),
                ),
            ],
        ),
    ]
