# Generated by Django 4.2.9 on 2024-01-30 16:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("promotions", "0002_promotioncode"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="promotion",
            options={"verbose_name": "Промо-акция", "verbose_name_plural": "Промо-акции"},
        ),
        migrations.AlterModelOptions(
            name="promotioncode",
            options={"verbose_name": "Код промо-акции", "verbose_name_plural": "Коды промо-акции"},
        ),
        migrations.AlterField(
            model_name="promotioncode",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True, verbose_name="Дата создания"),
        ),
    ]
