# Generated by Django 4.2.9 on 2024-02-01 18:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("promotions", "0003_alter_promotion_options_alter_promotioncode_options_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="promotion",
            name="name_ru",
            field=models.CharField(max_length=100, null=True, verbose_name="Название"),
        ),
        migrations.AddField(
            model_name="promotion",
            name="name_uz",
            field=models.CharField(max_length=100, null=True, verbose_name="Название"),
        ),
    ]
