# Generated by Django 4.2.9 on 2024-02-06 11:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("promotions", "0004_promotion_name_ru_promotion_name_uz"),
    ]

    operations = [
        migrations.AddField(
            model_name="promotion",
            name="conditions",
            field=models.TextField(default="879", verbose_name="Условия"),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="promotion",
            name="mask",
            field=models.CharField(default="879", verbose_name="Начальные символы (маска)"),
            preserve_default=False,
        ),
    ]
