# Generated by Django 4.2.9 on 2024-02-12 07:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("promotions", "0005_promotion_conditions_promotion_mask"),
    ]

    operations = [
        migrations.AddField(
            model_name="promotion",
            name="conditions_ru",
            field=models.TextField(null=True, verbose_name="Условия"),
        ),
        migrations.AddField(
            model_name="promotion",
            name="conditions_uz",
            field=models.TextField(null=True, verbose_name="Условия"),
        ),
    ]
