# Generated by Django 4.2.9 on 2024-01-30 12:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0002_telegramuser"),
    ]

    operations = [
        migrations.AddField(
            model_name="telegramuser",
            name="is_active",
            field=models.BooleanField(default=True),
        ),
    ]
