# Generated by Django 4.2.9 on 2024-01-30 16:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0003_telegramuser_is_active"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="telegramuser",
            options={"verbose_name": "Телеграм пользователь", "verbose_name_plural": "Телеграм пользователи"},
        ),
    ]
