# Generated by Django 4.2.9 on 2024-03-19 13:50

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0006_admintelegramusers"),
    ]

    operations = [
        migrations.AddField(
            model_name="notification",
            name="description_ru",
            field=ckeditor.fields.RichTextField(blank=True, max_length=1023, null=True),
        ),
        migrations.AddField(
            model_name="notification",
            name="description_uz",
            field=ckeditor.fields.RichTextField(blank=True, max_length=1023, null=True),
        ),
    ]
