# Generated by Django 4.2.9 on 2024-03-19 14:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0007_notification_description_ru_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="admintelegramusers",
            name="language",
            field=models.CharField(default="uz", max_length=2),
        ),
    ]
